# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
labels:
  org.opencontainers.image.title: "IoTaWatt MQTT bridge"
  org.opencontainers.image.description: "Bridge for IoTaWatt devices into HA's MQTT"
  org.opencontainers.image.source: "https://github.com/tabrisnet/iwMQTT"
  org.opencontainers.image.licenses: "GNU GPL 2.0"
args:
  TEMPIO_VERSION: "2024.11.2"
