# Build arguments
ARG BUILD_FROM BUILD_ARCH BUILD_DESCRIPTION BUILD_NAME BUILD_VERSION

FROM alpine:3.21

RUN apk add --no-cache --update perl-anyevent-http perl-module-pluggable perl-sub-name perl-yaml-tiny perl-json-xs

COPY entrypoint.sh iotawatt_config.yaml.gtmpl config.yaml CPAN iwMQTT.pl /

ADD entrypoint.sh /
RUN chmod +x /entrypoint.sh

# Labels
LABEL \
    io.hass.name="${BUILD_NAME}" \
    io.hass.description="${BUILD_DESCRIPTION}" \
    io.hass.arch="${BUILD_ARCH}" \
    io.hass.type="addon" \
    io.hass.version=${BUILD_VERSION}

ENTRYPOINT ["/bin/sh", "-c", "/entrypoint.sh"]
